// Auto-generated by OpenLane
module compute_core(
`ifdef USE_POWER_PINS
  inout VPWR,
  inout VGND,
`endif
  input clk,
  input rst,
  input[7:0] pixel_in,
  input valid_in,
  input weight_wr,
  input[1:0] weight_addr,
  input[7:0] weight_din,
  output[127:0] result_data,
  output result_valid
);
endmodule
