// Auto-generated by OpenLane
module cnn_top(
`ifdef USE_POWER_PINS
  inout VPWR,
  inout VGND,
`endif
  input clk,
  input rst,
  input s_awvalid,
  output s_awready,
  input[31:0] s_awaddr,
  input s_wvalid,
  output s_wready,
  input[31:0] s_wdata,
  input[3:0] s_wstrb,
  output s_bvalid,
  input s_bready,
  output[1:0] s_bresp,
  input s_arvalid,
  output s_arready,
  input[31:0] s_araddr,
  output s_rvalid,
  input s_rready,
  output[31:0] s_rdata,
  output[1:0] s_rresp
);
endmodule
