// ============================================================
// mac_llm_A.v
// Generated by: Claude Sonnet 4.6
// Codefest 4 — CLLM Task 1 (LLM A output)
// Module: mac — INT8 Multiply-Accumulate unit
// ============================================================

module mac (
    input  wire              clk,
    input  wire              rst,
    input  wire signed [7:0] a,
    input  wire signed [7:0] b,
    output reg  signed [31:0] out
);

    wire signed [15:0] product;
    assign product = a * b;

    // Uses plain 'always' instead of 'always_ff' — synthesizable
    // but incorrect for strict SystemVerilog (see mac_code_review.md)
    always @(posedge clk) begin
        if (rst)
            out <= 32'sd0;
        else
            out <= out + {{16{product[15]}}, product};
    end

endmodule
