// ============================================================
// mac_llm_B.v
// Generated by: GPT-4o
// Codefest 4 — CLLM Task 1 (LLM B output)
// Module: mac — INT8 Multiply-Accumulate unit
// ============================================================

module mac (
    input  logic        clk,
    input  logic        rst,
    input  logic [7:0]  a,       // Missing 'signed' — multiply treated as unsigned
    input  logic [7:0]  b,       // Missing 'signed' — multiply treated as unsigned
    output logic [31:0] out      // Missing 'signed' — accumulator unsigned
);

    always_ff @(posedge clk) begin
        if (rst)
            out <= 32'h0;
        else
            out <= out + {16'h0, a * b};  // Zero-extension loses sign of negative products
    end

endmodule
